# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

script = <<SCRIPT
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", inline: script

  config.vm.box = "chef/centos-6.5"

  config.omnibus.chef_version = :latest

  config.berkshelf.enabled = true

  config.vm.define :host1 do | host1 |
    host1.vm.hostname = "zabbix-server"
    host1.vm.network :private_network, ip: "192.168.33.10"
    host1.vm.provision :chef_solo do |chef|
      chef.run_list = %w[
          recipe[database::mysql]
          recipe[zabbix_introduction2::default]          
          recipe[zabbix_introduction2::server]
          recipe[zabbix_introduction2::server_conf]
      ]
=begin
       chef.run_list = %w[
          recipe[zabbix_introduction2::default]
          recipe[database::mysql]
          recipe[mysql::server]
          recipe[zabbix22::base]
          recipe[zabbix22::server]
          recipe[zabbix22::web]
          recipe[zabbix22::database]
          recipe[zabbix22::agent]
          recipe[zabbix22::service]
        ]
=end
    end
  end

  config.vm.define :host2 do | host2 |
    host2.vm.hostname = "zabbix-agent"
    host2.vm.network :private_network, ip: "192.168.33.20"
    host2.vm.provision :chef_solo do |chef|
      chef.run_list = %w[
          recipe[zabbix_introduction2::default]
          recipe[zabbix_introduction2::agent]
          recipe[zabbix_introduction2::agent_conf]
    ]
    end
  end

  config.vm.define :host3 do | host3 |
    host3.vm.hostname = "zabbix-proxy"
    host3.vm.network :private_network, ip: "192.168.33.30"
    host3.vm.provision :chef_solo do |chef|
      chef.run_list = %w[
          recipe[zabbix_introduction2::default]
          recipe[zabbix_introduction2::proxy]
      ]
    end
  end
end
