# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

script = <<SCRIPT
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", inline: script

  config.vm.hostname = "zabbix"

  config.vm.box = "chef/centos-6.5"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.omnibus.chef_version = :latest

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.run_list = %w[
        recipe[database::mysql]
        recipe[zabbix_introduction::default]
        recipe[zabbix_introduction::server]
        recipe[zabbix_introduction::server_conf]
    ]
  end
end
